---
apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    name: console
spec:
  ports:
    - port: 9090
      name: http
    - port: 9443
      name: https
  selector:
    app: console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console
          image: minio/mc:latest
          imagePullPolicy: "IfNotPresent"
          command: ["sh", "-c"]
          args:
            - |
              mc alias set myminio http://gitlab-minio:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY && \
              mc ls myminio
          env:
            - name: MINIO_SERVER_HOST
              value: "gitlab-minio"
            - name: MINIO_SERVER_PORT_NUMBER
              value: "9000"
            - name: MINIO_ACCESS_KEY
              value: "admin"
            - name: MINIO_SECRET_KEY
              value: "password"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minioconsole
spec:
  ingressClassName: "system-ingress"
  rules:
    - host: "minio.homelab.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console
                port:
                  name: http