apiVersion: v1
kind: Namespace
metadata:
  name: minio

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: rancher.io/local-path

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: minio
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/local-storage/minio # Убедитесь, что этот путь существует на узле

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args: ["server", "/data"]
          env:
            - name: MINIO_ACCESS_KEY
              value: "minio-access-key" # Замените на ваш ключ
            - name: MINIO_SECRET_KEY
              value: "minio-secret-key" # Замените на ваш секрет
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: local-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000 # Выберите порт между 30000 и 32767
  selector:
    app: minio

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: minio.example.com # Замените на ваш домен
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
  tls:
    - hosts:
        - minio.example.com
      secretName: minio-tls # Убедитесь, что этот секрет существует
